### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by birdbrainiac** [PrimalZed/character-sheet-generator#13]
I don't see the version number anywhere in the porgram. It would be handy for this to be displayed under the Help menu.

And yes, I still find this program extremely useful. (GiGs from roll20 forums)

**Comment by PrimalZed** [comment]
I added version to the menu in new release 0.6.0.

I'm not sure how that's useful, really. Are you working in multiple versions of the app?

**Comment by birdbrainiac** [comment]
No, but I was writing a tutorial for it, which drew me back to the releases page, and I realised I didn't know which version I had installed. It's in the filename, but that could be changed.
