### ISSUE TITLE
Partials Remembered - but for how long?

### ISSUE THREAD

**Issue by birdbrainiac** [PrimalZed/character-sheet-generator#18]
When you change the name of a Partial, and refresh the folder list, that Partial is still remembered. 
For instance, I had one partial named closure.handlebars, and it was called in my program.

Then I changed its name to end.handlebars, so closure.handlebars didn't exist any more.
But the handlebars file still contained calls to closure, and still worked and generated a proper html file.  

I'm guessing that the partials files are being added to the projects, but are not being removed when deleted.

**Comment by PrimalZed** [comment]
Updated it so it no longer "remembers" partials after generating output
