### ISSUE TITLE
Partials detection is not ideal

### ISSUE THREAD

**Issue by birdbrainiac** [PrimalZed/character-sheet-generator#19]
When trying out Partials I discovered a little gotcha. A new Partial isn't automatically detected when you click the Generate button. They are only detected when you click the Partials Change Folder button. You can select the same folder.

It would be nice if the generate button automatically refreshed the partals before doing the Generate stuff.

**Comment by PrimalZed** [comment]
Added a refresh button next to the partials directory button, and also use latest files from partials directory on every generate.
