### ISSUE TITLE
Crashing with 0.62, Partials

### ISSUE THREAD

**Issue by birdbrainiac** [PrimalZed/character-sheet-generator#21]
I am having crashes and I think the cause is the new Partials update.

If I try to change the Eoot Directory, I am hit with an error. 
After getting past the error, the Partials folder still points to the old one and has the old partials listed.
    (Note: there;s no way to check None in Partials any more - a Clear button should probably be added)
When I try to change the Partials directory to something in the new folder, it's hit & miss whether the program locks up or accepts the new folder.

**Comment by PrimalZed** [comment]
Set up new release 0.6.3 to fix it
