### ISSUE TITLE
0.6.3 crashes and wont run

### ISSUE THREAD

**Issue by birdbrainiac** [PrimalZed/character-sheet-generator#23]
When I try to run 0.6.3 I get an error, and haven't run it yet.
![image](https://github.com/PrimalZed/character-sheet-generator/assets/38135275/c2018f11-c037-4d14-bc02-a399d02cb48f)

**Comment by PrimalZed** [comment]
I built a new exe and uploaded, but when i downloaded it back from github, the Windows Security claims it found a virus in it:
![image](https://github.com/PrimalZed/character-sheet-generator/assets/4495480/79e74f92-fd1d-451e-91b5-5317b86da448)

I'll try to work out what's going on with that.

**Comment by PrimalZed** [comment]
It looks like this sort of false positives have occurred before on electron apps (such as this one):
https://github.com/electron-userland/electron-builder/issues/6474

When people last reported the issue in that thread last February, it stopped occurring after a couple of days. Presumably, Windows Defender updated something. Maybe try downloading/scanning this exe after a week or so?

I also submitted the exe to https://www.microsoft.com/en-us/wdsi/filesubmission so they can hopefully clear it. I don't think that will carry over to new exe files for further subsequent versions, though.

**Comment by PrimalZed** [comment]
Submitting the file to Microsoft for a scan seems to have cleared it. They gave me these instructions:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

I think you can also update security version in the Microsoft Defender gui.

**Comment by birdbrainiac** [comment]
That loaded!
