### ISSUE TITLE
Nested each or Repeat

### ISSUE THREAD

**Issue by birdbrainiac** [PrimalZed/character-sheet-generator#3]
Are you still willing to work on this. It's my primary sheet creation tool, but one thing I've never been able to figure out. Is it possible to nest each inside each, or each inside repeat or vice-versa? 

Here's some code that doesn't work, for example:
` {{#repeat count=6 start=1}}
        <span>Ability: </span>
        <select name="attr_ability{{@index}}">
            <option value="" selected>(Choose)</option>
            {{#each abilities}}
            <option>{{this.name}}</option>
            {{/each}}
        </select>
    {{/repeat}}`

**Comment by PrimalZed** [comment]
As discussed separately - using `@root` gets back to the root object when you're in some other context.
